### ISSUE TITLE
yarn install error: `ReferenceError: Request is not defined`

### ISSUE THREAD

**Issue by remainstheday** [borisno2/keystone-in-next-auth-demo#1]
on the `in-supabase` branch I get the following error while trying to run `yarn install`

`ReferenceError: Request is not defined
    at Object.<anonymous> (/Desktop/keystone-in-next-auth-demo/node_modules/next/dist/server/web/spec-extension/request.js:12:27)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/trentonk/Desktop/keystone-in-next-auth-demo/node_modules/next/server.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

**Comment by borisno2** [comment]
Hey @remainstheday 
I have set it up using pnpm, are you able to give pnpm a go to see if that resolves it?
